/**
 * H2 `id` values in each article body (`seed/bodies.tsx`), in document order.
 * Keep in sync when adding or renaming sections — `validateEditorialCorpus` compares to `toc`.
 */
export const EDITORIAL_BODY_SECTION_IDS: Record<string, readonly string[]> = {
  "what-blood-tests-matter-for-hair-loss": [
    "why-selective",
    "iron-and-blood-count",
    "thyroid",
    "inflammation-nutrition",
    "fitting-together",
    "not-medical-advice",
    "when-specialist",
  ],
  "ferritin-and-hair-loss": [
    "what-ferritin-is",
    "shedding-context",
    "targets-and-ranges",
    "with-thyroid",
    "supplements",
    "summary",
  ],
  "thyroid-hair-loss-explained": [
    "how-thyroid-affects-hair",
    "common-tests",
    "subclinical",
    "normal-tests-still-shedding",
    "iron-and-thyroid",
    "next-steps",
  ],
  "dht-and-androgenetic-alopecia": [
    "pattern-recognition",
    "dht-role",
    "not-only-men",
    "labs",
    "treatment-context",
    "expectations",
  ],
  "diffuse-thinning-in-women": [
    "patterns",
    "overlap",
    "labs-selective",
    "androgenetic",
    "procedural",
    "support",
  ],
  "prp-vs-exosomes": [
    "what-prp-is",
    "exosomes-claims",
    "evidence",
    "safety",
    "who-benefits",
    "before-procedure",
    "labs",
  ],
  "finasteride-vs-saw-palmetto": [
    "finasteride-mechanism",
    "women",
    "saw-palmetto",
    "not-substitute",
    "dht-context",
    "monitoring",
    "takeaway",
  ],
  "hli-vs-hairaudit": [
    "hli-focus",
    "hairaudit-focus",
    "overlap",
    "same-ecosystem",
    "reading",
    "when-hairaudit",
    "not-advice",
  ],
  "postpartum-shedding-when-to-reassure-vs-when-to-test": [
    "normal-postpartum-shedding",
    "when-reassurance-fits",
    "red-flags-testing",
    "overlap-thyroid-iron",
    "hair-cycle-timelines",
    "partner-with-clinician",
    "what-this-is-not",
  ],
  "telogen-effluvium-after-illness-or-stress": [
    "what-te-triggers",
    "timing-after-stressor",
    "overlap-pattern-loss",
    "labs-when-indicated",
    "prognosis",
    "emotional-load",
    "when-specialist",
  ],
  "vitamin-d-b12-folate-what-labs-may-mean-for-hair": [
    "why-context-matters",
    "vitamin-d",
    "b12-folate",
    "interpretation-limits",
    "with-iron-thyroid",
    "supplementation-caution",
    "constructive-next-steps",
  ],
  "scalp-inflammation-and-shedding": [
    "inflammation-and-cycle",
    "common-presentations",
    "overlap-shedding-aga",
    "examination-themes",
    "treatment-prescriber-led",
    "alongside-systemic-health",
    "when-urgent-care",
  ],
  "minoxidil-mechanism-and-realistic-timelines": [
    "mechanism-overview",
    "who-uses-it",
    "timelines-shedding-phase",
    "realistic-outcomes",
    "adherence",
    "combination-context",
    "not-substitute-diagnosis",
  ],
  "post-transplant-shock-loss-and-expectations": [
    "shock-loss-what-it-is",
    "typical-timing",
    "different-graft-concerns",
    "communication-with-team",
    "labs-systemic-health",
    "longitudinal-expectations",
    "emotional-expectations",
  ],
  "oral-anti-androgens-in-women-specialist-led-context": [
    "scope-specialist-led",
    "why-not-self-start",
    "drug-classes-high-level",
    "monitoring-safety",
    "fertility-pregnancy",
    "relation-pattern-hair-loss",
    "constructive-questions",
  ],
  "receding-hairline-vs-mature-hairline": [
    "why-this-question-comes-up-so-often",
    "what-a-mature-hairline-usually-looks-like",
    "what-early-recession-usually-looks-like",
    "what-clinicians-look-for-and-key-differences",
    "when-it-is-worth-acting-early",
    "the-role-of-dht-and-genetics",
    "summary-and-next-steps",
  ],
  "crown-thinning-why-it-can-be-harder-to-treat": [
    "why-crown-thinning-is-often-noticed-late",
    "why-crown-thinning-can-feel-harder-to-improve",
    "what-usually-helps-most",
    "when-crown-thinning-suggests-broader-pattern-loss",
    "when-to-seek-professional-review",
    "understanding-the-biology-dht-miniaturisation-and-the-crown",
    "setting-realistic-expectations-framework-for-progress",
    "next-steps-and-further-reading",
  ],
  "does-trt-cause-hair-loss-or-unmask-it": [
    "why-this-question-matters",
    "what-trt-changes-biologically",
    "why-trt-does-not-affect-everyone-equally",
    "cause-versus-unmasking",
    "what-clinicians-look-at",
    "what-to-do-next-with-your-prescriber",
    "takeaways-and-where-to-read-next",
  ],
  "normal-testosterone-and-androgen-sensitive-hair-loss": [
    "why-normal-testosterone-does-not-rule-it-out",
    "why-pattern-matters-more-than-one-number",
    "how-this-misunderstanding-delays-action",
    "men-and-women-can-both-be-affected",
    "what-a-better-assessment-looks-like",
    "the-role-of-dht-and-local-conversion",
    "takeaways-and-further-reading",
  ],
  "oral-minoxidil-vs-topical-minoxidil": [
    "what-both-forms-are-trying-to-do",
    "topical-minoxidil-in-practice",
    "oral-minoxidil-in-practice",
    "who-may-lean-toward-one-route-or-the-other",
    "what-not-to-compare-too-simplistically",
    "monitoring-safety-and-side-effects",
    "next-steps-and-further-reading",
  ],
  "dutasteride-for-hair-loss-when-it-enters-the-conversation": [
    "where-dutasteride-sits-in-the-discussion",
    "when-dutasteride-may-come-up",
    "what-patients-often-misunderstand",
    "how-dutasteride-fits-into-broader-planning",
    "questions-worth-asking-your-clinician",
    "expectations-patience-and-honest-outcomes",
    "takeaways-and-best-next-reads",
  ],
  "postpartum-hair-loss-vs-female-pattern-thinning": [
    "what-postpartum-shedding-usually-looks-like",
    "what-female-pattern-thinning-usually-looks-like",
    "when-the-line-between-them-blurs",
    "comparing-the-two-at-a-glance",
    "when-to-reassess-instead-of-only-reassure",
    "what-next-steps-may-look-like",
    "emotional-context-and-clinical-clarity",
  ],
  "hair-shedding-vs-hair-breakage": [
    "what-is-hair-shedding",
    "what-is-hair-breakage",
    "clues-that-help-you-tell-them-apart",
    "why-the-difference-matters",
    "when-both-can-happen-together",
    "a-practical-self-assessment-framework",
    "key-takeaways-and-next-reads",
  ],
};
