/**
 * H2 `id` values in each article body (`seed/bodies.tsx`), in document order.
 * Keep in sync when adding or renaming sections — `validateEditorialCorpus` compares to `toc`.
 */
export const EDITORIAL_BODY_SECTION_IDS: Record<string, readonly string[]> = {
  "what-blood-tests-matter-for-hair-loss": [
    "why-selective",
    "iron-and-blood-count",
    "thyroid",
    "inflammation-nutrition",
    "fitting-together",
    "not-medical-advice",
    "when-specialist",
  ],
  "ferritin-and-hair-loss": [
    "what-ferritin-is",
    "shedding-context",
    "targets-and-ranges",
    "with-thyroid",
    "supplements",
    "summary",
  ],
  "thyroid-hair-loss-explained": [
    "how-thyroid-affects-hair",
    "common-tests",
    "subclinical",
    "normal-tests-still-shedding",
    "iron-and-thyroid",
    "next-steps",
  ],
  "dht-and-androgenetic-alopecia": [
    "pattern-recognition",
    "dht-role",
    "not-only-men",
    "labs",
    "treatment-context",
    "expectations",
  ],
  "diffuse-thinning-in-women": [
    "patterns",
    "overlap",
    "labs-selective",
    "androgenetic",
    "procedural",
    "support",
  ],
  "prp-vs-exosomes": [
    "what-prp-is",
    "exosomes-claims",
    "evidence",
    "safety",
    "who-benefits",
    "before-procedure",
    "labs",
  ],
  "finasteride-vs-saw-palmetto": [
    "finasteride-mechanism",
    "women",
    "saw-palmetto",
    "not-substitute",
    "dht-context",
    "monitoring",
    "takeaway",
  ],
  "hli-vs-hairaudit": [
    "hli-focus",
    "hairaudit-focus",
    "overlap",
    "same-ecosystem",
    "reading",
    "when-hairaudit",
    "not-advice",
  ],
  "postpartum-shedding-when-to-reassure-vs-when-to-test": [
    "normal-postpartum-shedding",
    "when-reassurance-fits",
    "red-flags-testing",
    "overlap-thyroid-iron",
    "hair-cycle-timelines",
    "partner-with-clinician",
    "what-this-is-not",
  ],
  "telogen-effluvium-after-illness-or-stress": [
    "what-te-triggers",
    "timing-after-stressor",
    "overlap-pattern-loss",
    "labs-when-indicated",
    "prognosis",
    "emotional-load",
    "when-specialist",
  ],
  "vitamin-d-b12-folate-what-labs-may-mean-for-hair": [
    "why-context-matters",
    "vitamin-d",
    "b12-folate",
    "interpretation-limits",
    "with-iron-thyroid",
    "supplementation-caution",
    "constructive-next-steps",
  ],
  "scalp-inflammation-and-shedding": [
    "inflammation-and-cycle",
    "common-presentations",
    "overlap-shedding-aga",
    "examination-themes",
    "treatment-prescriber-led",
    "alongside-systemic-health",
    "when-urgent-care",
  ],
  "minoxidil-mechanism-and-realistic-timelines": [
    "mechanism-overview",
    "who-uses-it",
    "timelines-shedding-phase",
    "realistic-outcomes",
    "adherence",
    "combination-context",
    "not-substitute-diagnosis",
  ],
  "post-transplant-shock-loss-and-expectations": [
    "shock-loss-what-it-is",
    "typical-timing",
    "different-graft-concerns",
    "communication-with-team",
    "labs-systemic-health",
    "longitudinal-expectations",
    "emotional-expectations",
  ],
  "oral-anti-androgens-in-women-specialist-led-context": [
    "scope-specialist-led",
    "why-not-self-start",
    "drug-classes-high-level",
    "monitoring-safety",
    "fertility-pregnancy",
    "relation-pattern-hair-loss",
    "constructive-questions",
  ],
};
