import type { AdaptiveQuestion } from "./adaptiveTypes";

export const ADAPTIVE_QUESTION_BANK: AdaptiveQuestion[] = [
  {
    id: "sex_at_birth",
    kind: "base",
    prompt: "What sex were you assigned at birth?",
    answerType: "single_select",
    options: [
      { value: "female", label: "Female" },
      { value: "male", label: "Male" },
      { value: "intersex", label: "Intersex" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
    validation: { required: true },
  },
  {
    id: "dob",
    kind: "base",
    prompt: "What is your date of birth?",
    answerType: "date",
    validation: { required: true },
  },
  {
    id: "chief_concern",
    kind: "base",
    prompt: "What concerns you most about your hair or scalp right now?",
    answerType: "single_select",
    options: [
      { value: "shedding", label: "Increased shedding" },
      { value: "thinning", label: "Thinning density" },
      { value: "receding_hairline", label: "Receding hairline or temples" },
      { value: "crown_loss", label: "Crown thinning" },
      { value: "patchy_loss", label: "Patchy hair loss" },
      { value: "scalp_symptoms", label: "Scalp symptoms" },
      { value: "mixed_unsure", label: "A mix of changes / not sure" },
    ],
    validation: { required: true },
  },
  {
    id: "onset_timing",
    kind: "base",
    prompt: "When did you first notice this change?",
    answerType: "single_select",
    options: [
      { value: "less_than_6_weeks", label: "Less than 6 weeks ago" },
      { value: "6_weeks_to_3_months", label: "6 weeks to 3 months ago" },
      { value: "3_to_6_months", label: "3 to 6 months ago" },
      { value: "6_to_12_months", label: "6 to 12 months ago" },
      { value: "more_than_12_months", label: "More than 12 months ago" },
    ],
    validation: { required: true },
  },
  {
    id: "progression_speed",
    kind: "base",
    prompt: "How has it been progressing?",
    answerType: "single_select",
    options: [
      { value: "sudden", label: "Sudden" },
      { value: "gradual", label: "Gradual" },
      { value: "fluctuating", label: "Fluctuating" },
      { value: "rapidly_worsening", label: "Rapidly worsening" },
    ],
    validation: { required: true },
  },
  {
    id: "pattern_distribution",
    kind: "base",
    prompt: "Which areas are most affected?",
    answerType: "multi_select",
    options: [
      { value: "temples", label: "Temples" },
      { value: "frontal_hairline", label: "Frontal hairline" },
      { value: "crown", label: "Crown" },
      { value: "center_part", label: "Center part / midline" },
      { value: "diffuse_top", label: "Diffuse on top" },
      { value: "diffuse_all_over", label: "Diffuse all over" },
      { value: "edges", label: "Edges / traction zones" },
      { value: "eyebrows", label: "Eyebrows" },
    ],
    validation: { required: true },
  },
  {
    id: "active_shedding_now",
    kind: "base",
    prompt: "Are you currently noticing active shedding?",
    answerType: "boolean",
    helpText: "For example, more hairs on your pillow, in the shower, or on your brush.",
  },
  {
    id: "breakage_over_shedding",
    kind: "base",
    prompt: "Do the hairs seem to be snapping or breaking rather than shedding from the root?",
    answerType: "boolean",
  },

  {
    id: "recent_illness",
    kind: "base",
    prompt: "Have you had a significant illness in the last 6 months?",
    answerType: "boolean",
  },
  {
    id: "covid_or_high_fever",
    kind: "base",
    prompt: "Have you had COVID, a high fever, or a significant infection in the last 6 months?",
    answerType: "boolean",
  },
  {
    id: "recent_surgery",
    kind: "base",
    prompt: "Have you had surgery or a general anaesthetic in the last 6 months?",
    answerType: "boolean",
  },
  {
    id: "recent_stress_event",
    kind: "base",
    prompt: "Have you had a major emotional stress event in the last 6 months?",
    answerType: "boolean",
  },
  {
    id: "rapid_weight_loss",
    kind: "base",
    prompt: "Have you had rapid weight loss or a major diet change recently?",
    answerType: "boolean",
  },
  {
    id: "medication_change_recently",
    kind: "base",
    prompt: "Have you started, stopped, or changed any medications, hormones, or supplements recently?",
    answerType: "boolean",
  },

  {
    id: "scalp_symptoms",
    kind: "base",
    prompt: "Are you noticing any scalp symptoms?",
    answerType: "multi_select",
    options: [
      { value: "itch", label: "Itch" },
      { value: "burning", label: "Burning" },
      { value: "pain", label: "Pain or tenderness" },
      { value: "white_flakes", label: "White flakes" },
      { value: "yellow_greasy_scale", label: "Yellow / greasy scale" },
      { value: "redness", label: "Redness" },
      { value: "pustules", label: "Pimples / pustules" },
      { value: "crusting", label: "Crusting" },
      { value: "none", label: "None of these" },
    ],
  },

  {
    id: "family_history",
    kind: "conditional",
    prompt: "Is there a family history of hair loss on either side of your family?",
    answerType: "single_select",
    options: [
      { value: "none_known", label: "None known" },
      { value: "mothers_side", label: "Yes, on my mother's side" },
      { value: "fathers_side", label: "Yes, on my father's side" },
      { value: "both_sides", label: "Yes, on both sides" },
      { value: "unsure", label: "I'm not sure" },
    ],
    showWhen: [{ fact: "suspected_patterned_loss", operator: "eq", value: true }],
  },

  {
    id: "female_hormonal_context",
    kind: "conditional",
    prompt:
      "Are there any hormonal, reproductive, or endocrine changes you think may be relevant to your hair changes?",
    answerType: "single_select",
    sensitive: true,
    patientMaySkip: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
    showWhen: [{ fact: "is_female", operator: "eq", value: true }],
  },
  {
    id: "postpartum_recent_gate",
    kind: "branch_followup",
    prompt: "Have you given birth in the last 12 months?",
    answerType: "single_select",
    sensitive: true,
    patientMaySkip: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "unsure", label: "Unsure" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
    showWhen: [{ fact: "female_hormonal_gate_open", operator: "eq", value: true }],
  },
  {
    id: "months_since_delivery",
    kind: "branch_followup",
    prompt: "Roughly how long has it been since delivery?",
    answerType: "single_select",
    sensitive: true,
    patientMaySkip: true,
    options: [
      { value: "under_3_months", label: "Under 3 months" },
      { value: "3_to_6_months", label: "3 to 6 months" },
      { value: "6_to_12_months", label: "6 to 12 months" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
    showWhen: [{ fact: "postpartum_recent_gate", operator: "eq", value: "yes" }],
  },
  {
    id: "breastfeeding_status",
    kind: "branch_followup",
    prompt: "Is breastfeeding or weaning part of the current picture?",
    answerType: "single_select",
    sensitive: true,
    patientMaySkip: true,
    options: [
      { value: "currently_breastfeeding", label: "Currently breastfeeding" },
      { value: "partially_weaning", label: "Partially weaning / mixed feeding" },
      { value: "stopped_within_3_months", label: "Stopped within the last 3 months" },
      { value: "stopped_over_3_months", label: "Stopped more than 3 months ago" },
      { value: "not_applicable", label: "Not applicable" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
    showWhen: [{ fact: "postpartum_recent_gate", operator: "eq", value: "yes" }],
  },
  {
    id: "hormonal_contraception_change_gate",
    kind: "branch_followup",
    prompt: "In the last year, did you start, stop, or change hormonal contraception or HRT?",
    answerType: "single_select",
    sensitive: true,
    patientMaySkip: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "unsure", label: "Unsure" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
    showWhen: [{ fact: "female_hormonal_gate_open", operator: "eq", value: true }],
  },
  {
    id: "hormonal_change_vs_hair_timing",
    kind: "branch_followup",
    prompt: "How did that hormone change line up with your hair change?",
    answerType: "single_select",
    sensitive: true,
    patientMaySkip: true,
    options: [
      { value: "before_hair_change", label: "Before the hair change" },
      { value: "around_same_time", label: "Around the same time" },
      { value: "after_hair_change", label: "After the hair change" },
      { value: "unsure", label: "Unsure" },
    ],
    showWhen: [{ fact: "hormonal_contraception_change_gate", operator: "eq", value: "yes" }],
  },
  {
    id: "stress_shedding_delay_pattern",
    kind: "branch_followup",
    prompt:
      "Did your shedding start 2 to 4 months after a major stress period, illness, surgery, or major life disruption?",
    answerType: "single_select",
    sensitive: true,
    patientMaySkip: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "unsure", label: "Unsure" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
    showWhen: [
      { fact: "female_hormonal_gate_open", operator: "eq", value: true },
      { fact: "suspected_shedding", operator: "eq", value: true },
    ],
  },
  {
    id: "pituitary_red_flag_followup",
    kind: "branch_followup",
    prompt:
      "Have you had absent periods when not pregnant, breastfeeding, or on hormonal suppression, or any milky nipple discharge, new severe headaches, or visual changes?",
    answerType: "single_select",
    sensitive: true,
    patientMaySkip: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "unsure", label: "Unsure" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
    showWhen: [{ fact: "female_hormonal_gate_open", operator: "eq", value: true }],
  },
  {
    id: "hirsutism_severity",
    kind: "branch_followup",
    prompt:
      "If facial or body hair change is part of the picture, how noticeable does it feel to you?",
    answerType: "single_select",
    sensitive: true,
    patientMaySkip: true,
    options: [
      { value: "not_really", label: "Not really / not relevant" },
      { value: "mild", label: "Mild" },
      { value: "moderate", label: "Moderate" },
      { value: "marked", label: "Marked" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
    helpText: "If this does not really apply, choose the first option or skip it.",
    showWhen: [{ fact: "possible_hirsutism_screen_trigger", operator: "eq", value: true }],
  },
  {
    id: "hirsutism_structured_check_opt_in",
    kind: "branch_followup",
    prompt:
      "If you want, would you be comfortable doing a brief private self-check of a few areas to make this more specific?",
    answerType: "single_select",
    sensitive: true,
    patientMaySkip: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
    helpText: "Optional. This adds a little more detail without using a full scoring system.",
    showWhen: [
      { fact: "possible_hirsutism_structured_followup", operator: "eq", value: true },
    ],
  },
  {
    id: "hirsutism_structured_regions",
    kind: "branch_followup",
    prompt:
      "Which areas feel more noticeably affected by coarser or darker hair growth?",
    answerType: "multi_select",
    sensitive: true,
    patientMaySkip: true,
    options: [
      { value: "upper_lip", label: "Upper lip" },
      { value: "chin_jawline", label: "Chin / jawline" },
      { value: "chest", label: "Chest" },
      { value: "around_nipples", label: "Around the nipples" },
      { value: "lower_abdomen", label: "Lower abdomen" },
      { value: "inner_thighs", label: "Inner thighs" },
      { value: "none", label: "None of these / not sure" },
    ],
    helpText: "Optional private self-check. Select only what clearly feels relevant.",
    showWhen: [
      { fact: "possible_hirsutism_structured_followup", operator: "eq", value: true },
      { fact: "hirsutism_structured_check_opt_in", operator: "eq", value: "yes" },
    ],
  },

  {
    id: "neutral_hormonal_context",
    kind: "conditional",
    prompt: "Are there any hormonal, reproductive, or endocrine changes you think may be relevant to your hair changes?",
    answerType: "boolean",
    sensitive: true,
    patientMaySkip: true,
    showWhen: [{ fact: "is_neutral_pathway", operator: "eq", value: true }],
  },
  {
    id: "tight_hairstyles_or_extensions",
    kind: "conditional",
    prompt: "Do you regularly wear tight hairstyles, braids, extensions, or wigs that place tension on the hairline?",
    answerType: "boolean",
    showWhen: [{ fact: "possible_breakage_pattern", operator: "eq", value: true }],
  },
  {
    id: "frequent_helmet_or_headgear",
    kind: "conditional",
    prompt: "Do you frequently wear helmets, tight caps, or other headgear?",
    answerType: "boolean",
    showWhen: [{ fact: "possible_breakage_pattern", operator: "eq", value: true }],
  },
  {
    id: "contact_sports_or_headgear_sport",
    kind: "conditional",
    prompt: "Do you participate in contact sports or sports with tight or repetitive headgear?",
    answerType: "boolean",
    showWhen: [{ fact: "possible_breakage_pattern", operator: "eq", value: true }],
  },
  {
    id: "heat_or_chemical_styling",
    kind: "conditional",
    prompt: "Do you frequently use harsh heat styling, bleaching, relaxing, or strong cosmetic treatments?",
    answerType: "boolean",
    showWhen: [{ fact: "possible_breakage_pattern", operator: "eq", value: true }],
  },

  {
    id: "treatment_history",
    kind: "conditional",
    prompt: "Have you used any hair-loss treatments before?",
    answerType: "multi_select",
    options: [
      { value: "finasteride", label: "Finasteride" },
      { value: "dutasteride", label: "Dutasteride" },
      { value: "topical_minoxidil", label: "Topical minoxidil" },
      { value: "oral_minoxidil", label: "Oral minoxidil" },
      { value: "prp", label: "PRP" },
      { value: "other", label: "Other" },
      { value: "none", label: "None" },
    ],
    showWhen: [{ fact: "suspected_patterned_loss", operator: "eq", value: true }],
  },
];
