import type { AdaptiveQuestion } from "./adaptiveTypes";

export const ADAPTIVE_QUESTION_BANK: AdaptiveQuestion[] = [
  {
    id: "sex_at_birth",
    kind: "base",
    prompt: "What sex were you assigned at birth?",
    answerType: "single_select",
    options: [
      { value: "female", label: "Female" },
      { value: "male", label: "Male" },
      { value: "intersex", label: "Intersex" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
    validation: { required: true },
  },
  {
    id: "dob",
    kind: "base",
    prompt: "What is your date of birth?",
    answerType: "date",
    validation: { required: true },
  },
  {
    id: "chief_concern",
    kind: "base",
    prompt: "What concerns you most about your hair or scalp right now?",
    answerType: "single_select",
    options: [
      { value: "shedding", label: "Increased shedding" },
      { value: "thinning", label: "Thinning density" },
      { value: "receding_hairline", label: "Receding hairline or temples" },
      { value: "crown_loss", label: "Crown thinning" },
      { value: "patchy_loss", label: "Patchy hair loss" },
      { value: "scalp_symptoms", label: "Scalp symptoms" },
      { value: "mixed_unsure", label: "A mix of changes / not sure" },
    ],
    validation: { required: true },
  },
  {
    id: "onset_timing",
    kind: "base",
    prompt: "When did you first notice this change?",
    answerType: "single_select",
    options: [
      { value: "less_than_6_weeks", label: "Less than 6 weeks ago" },
      { value: "6_weeks_to_3_months", label: "6 weeks to 3 months ago" },
      { value: "3_to_6_months", label: "3 to 6 months ago" },
      { value: "6_to_12_months", label: "6 to 12 months ago" },
      { value: "more_than_12_months", label: "More than 12 months ago" },
    ],
    validation: { required: true },
  },
  {
    id: "progression_speed",
    kind: "base",
    prompt: "How has it been progressing?",
    answerType: "single_select",
    options: [
      { value: "sudden", label: "Sudden" },
      { value: "gradual", label: "Gradual" },
      { value: "fluctuating", label: "Fluctuating" },
      { value: "rapidly_worsening", label: "Rapidly worsening" },
    ],
    validation: { required: true },
  },
  {
    id: "pattern_distribution",
    kind: "base",
    prompt: "Which areas are most affected?",
    answerType: "multi_select",
    options: [
      { value: "temples", label: "Temples" },
      { value: "frontal_hairline", label: "Frontal hairline" },
      { value: "crown", label: "Crown" },
      { value: "center_part", label: "Center part / midline" },
      { value: "diffuse_top", label: "Diffuse on top" },
      { value: "diffuse_all_over", label: "Diffuse all over" },
      { value: "edges", label: "Edges / traction zones" },
      { value: "eyebrows", label: "Eyebrows" },
    ],
    validation: { required: true },
  },
  {
    id: "active_shedding_now",
    kind: "base",
    prompt: "Are you currently noticing active shedding?",
    answerType: "boolean",
    helpText: "For example, more hairs on your pillow, in the shower, or on your brush.",
  },
  {
    id: "breakage_over_shedding",
    kind: "base",
    prompt: "Do the hairs seem to be snapping or breaking rather than shedding from the root?",
    answerType: "boolean",
  },

  {
    id: "recent_illness",
    kind: "base",
    prompt: "Have you had a significant illness in the last 6 months?",
    answerType: "boolean",
  },
  {
    id: "covid_or_high_fever",
    kind: "base",
    prompt: "Have you had COVID, a high fever, or a significant infection in the last 6 months?",
    answerType: "boolean",
  },
  {
    id: "recent_surgery",
    kind: "base",
    prompt: "Have you had surgery or a general anaesthetic in the last 6 months?",
    answerType: "boolean",
  },
  {
    id: "recent_stress_event",
    kind: "base",
    prompt: "Have you had a major emotional stress event in the last 6 months?",
    answerType: "boolean",
  },
  {
    id: "rapid_weight_loss",
    kind: "base",
    prompt: "Have you had rapid weight loss or a major diet change recently?",
    answerType: "boolean",
  },
  {
    id: "medication_change_recently",
    kind: "base",
    prompt: "Have you started, stopped, or changed any medications, hormones, or supplements recently?",
    answerType: "boolean",
  },

  {
    id: "scalp_symptoms",
    kind: "base",
    prompt: "Are you noticing any scalp symptoms?",
    answerType: "multi_select",
    options: [
      { value: "itch", label: "Itch" },
      { value: "burning", label: "Burning" },
      { value: "pain", label: "Pain or tenderness" },
      { value: "white_flakes", label: "White flakes" },
      { value: "yellow_greasy_scale", label: "Yellow / greasy scale" },
      { value: "redness", label: "Redness" },
      { value: "pustules", label: "Pimples / pustules" },
      { value: "crusting", label: "Crusting" },
      { value: "none", label: "None of these" },
    ],
  },

  {
    id: "family_history",
    kind: "conditional",
    prompt: "Is there a family history of hair loss on either side of your family?",
    answerType: "single_select",
    options: [
      { value: "none_known", label: "None known" },
      { value: "mothers_side", label: "Yes, on my mother's side" },
      { value: "fathers_side", label: "Yes, on my father's side" },
      { value: "both_sides", label: "Yes, on both sides" },
      { value: "unsure", label: "I'm not sure" },
    ],
    showWhen: [{ fact: "suspected_patterned_loss", operator: "eq", value: true }],
  },

  {
    id: "current_or_past_trt",
    kind: "conditional",
    prompt: "Have you used testosterone replacement therapy (TRT) currently or in the past?",
    answerType: "boolean",
    showWhen: [
      { fact: "is_male", operator: "eq", value: true },
      { fact: "suspected_patterned_loss", operator: "eq", value: true },
    ],
  },
  {
    id: "trt_start_context",
    kind: "branch_followup",
    prompt: "If yes, when did TRT start relative to your hair changes?",
    answerType: "single_select",
    patientMaySkip: true,
    options: [
      { value: "before_hair_change", label: "Before hair changes" },
      { value: "around_same_time", label: "Around the same time" },
      { value: "after_hair_change", label: "After hair changes began" },
      { value: "unsure", label: "Not sure" },
    ],
    showWhen: [{ fact: "current_or_past_trt", operator: "eq", value: true }],
  },
  {
    id: "testosterone_boosters",
    kind: "conditional",
    prompt: "Have you used testosterone boosters or similar performance products?",
    answerType: "boolean",
    showWhen: [
      { fact: "is_male", operator: "eq", value: true },
      { fact: "suspected_patterned_loss", operator: "eq", value: true },
    ],
  },
  {
    id: "sarms_or_anabolics",
    kind: "conditional",
    prompt: "Have you used SARMs, anabolic steroids, or similar agents?",
    answerType: "boolean",
    showWhen: [
      { fact: "is_male", operator: "eq", value: true },
      { fact: "suspected_patterned_loss", operator: "eq", value: true },
    ],
  },
  {
    id: "peptides_or_growth_agents",
    kind: "conditional",
    prompt: "Have you used peptides, growth agents, or bodybuilding hormone compounds?",
    answerType: "boolean",
    showWhen: [
      { fact: "is_male", operator: "eq", value: true },
      { fact: "suspected_patterned_loss", operator: "eq", value: true },
    ],
  },

  {
    id: "cycle_regularity",
    kind: "conditional",
    prompt: "How would you describe your menstrual cycles?",
    answerType: "single_select",
    sensitive: true,
    patientMaySkip: true,
    options: [
      { value: "regular", label: "Regular" },
      { value: "irregular", label: "Irregular" },
      { value: "missed_periods", label: "I miss periods" },
      { value: "not_applicable", label: "Not applicable" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
    showWhen: [
      { fact: "is_female", operator: "eq", value: true },
      { fact: "suspected_patterned_loss", operator: "eq", value: true },
    ],
  },
  {
    id: "heavy_periods",
    kind: "conditional",
    prompt: "Do you experience heavy menstrual bleeding?",
    answerType: "boolean",
    sensitive: true,
    patientMaySkip: true,
    showWhen: [
      { fact: "is_female", operator: "eq", value: true },
      { fact: "suspected_patterned_loss", operator: "eq", value: true },
    ],
  },
  {
    id: "reproductive_stage",
    kind: "conditional",
    prompt: "Which best describes your current life stage?",
    answerType: "single_select",
    sensitive: true,
    patientMaySkip: true,
    options: [
      { value: "premenopausal", label: "Premenopausal" },
      { value: "perimenopausal", label: "Perimenopausal" },
      { value: "menopausal", label: "Menopausal" },
      { value: "postpartum", label: "Postpartum" },
      { value: "not_applicable", label: "Not applicable / not sure" },
    ],
    showWhen: [
      { fact: "is_female", operator: "eq", value: true },
      { fact: "suspected_patterned_loss", operator: "eq", value: true },
    ],
  },
  {
    id: "postpartum_recent",
    kind: "conditional",
    prompt: "Have you given birth in the last 12 months?",
    answerType: "boolean",
    sensitive: true,
    patientMaySkip: true,
    showWhen: [
      { fact: "is_female", operator: "eq", value: true },
      { fact: "suspected_patterned_loss", operator: "eq", value: true },
    ],
  },
  {
    id: "unwanted_facial_hair",
    kind: "conditional",
    prompt: "Have you noticed unwanted facial hair growth?",
    answerType: "boolean",
    sensitive: true,
    patientMaySkip: true,
    showWhen: [
      { fact: "is_female", operator: "eq", value: true },
      { fact: "suspected_patterned_loss", operator: "eq", value: true },
    ],
  },
  {
    id: "increased_body_hair",
    kind: "conditional",
    prompt: "Have you noticed increased body hair in areas such as the chest, abdomen, or thighs?",
    answerType: "boolean",
    sensitive: true,
    patientMaySkip: true,
    showWhen: [
      { fact: "is_female", operator: "eq", value: true },
      { fact: "suspected_patterned_loss", operator: "eq", value: true },
    ],
  },
  {
    id: "jawline_acne_or_oily_skin",
    kind: "conditional",
    prompt: "Have you noticed persistent jawline acne or markedly oily skin?",
    answerType: "boolean",
    sensitive: true,
    patientMaySkip: true,
    showWhen: [
      { fact: "is_female", operator: "eq", value: true },
      { fact: "suspected_patterned_loss", operator: "eq", value: true },
    ],
  },
  {
    id: "known_pcos",
    kind: "conditional",
    prompt: "Have you ever been diagnosed with PCOS?",
    answerType: "boolean",
    sensitive: true,
    patientMaySkip: true,
    showWhen: [
      { fact: "is_female", operator: "eq", value: true },
      { fact: "suspected_patterned_loss", operator: "eq", value: true },
    ],
  },

  {
    id: "neutral_hormonal_context",
    kind: "conditional",
    prompt: "Are there any hormonal, reproductive, or endocrine changes you think may be relevant to your hair changes?",
    answerType: "boolean",
    sensitive: true,
    patientMaySkip: true,
    showWhen: [{ fact: "is_neutral_pathway", operator: "eq", value: true }],
  },

  {
    id: "vegetarian_or_vegan",
    kind: "conditional",
    prompt: "Do you follow a vegetarian or vegan diet?",
    answerType: "boolean",
    showWhen: [{ fact: "suspected_shedding", operator: "eq", value: true }],
  },
  {
    id: "restrictive_dieting",
    kind: "conditional",
    prompt: "Have you been restricting calories or dieting heavily?",
    answerType: "boolean",
    sensitive: true,
    patientMaySkip: true,
    showWhen: [{ fact: "suspected_shedding", operator: "eq", value: true }],
  },
  {
    id: "eating_disorder_history",
    kind: "conditional",
    prompt: "Have you ever had periods of disordered eating or significant under-eating that may be relevant?",
    answerType: "boolean",
    sensitive: true,
    patientMaySkip: true,
    showWhen: [{ fact: "suspected_shedding", operator: "eq", value: true }],
  },
  {
    id: "low_protein_intake",
    kind: "conditional",
    prompt: "Do you think your protein intake may be low?",
    answerType: "boolean",
    showWhen: [{ fact: "suspected_shedding", operator: "eq", value: true }],
  },
  {
    id: "low_iron_history",
    kind: "conditional",
    prompt: "Have you ever been told your iron or ferritin is low?",
    answerType: "boolean",
    showWhen: [{ fact: "suspected_shedding", operator: "eq", value: true }],
  },
  {
    id: "low_b12_history",
    kind: "conditional",
    prompt: "Have you ever been told your vitamin B12 is low?",
    answerType: "boolean",
    showWhen: [{ fact: "suspected_shedding", operator: "eq", value: true }],
  },
  {
    id: "low_vitamin_d_history",
    kind: "conditional",
    prompt: "Have you ever been told your vitamin D is low?",
    answerType: "boolean",
    showWhen: [{ fact: "suspected_shedding", operator: "eq", value: true }],
  },

  {
    id: "poor_sleep_quality",
    kind: "conditional",
    prompt: "Has your sleep quality been poor for a sustained period?",
    answerType: "boolean",
    showWhen: [{ fact: "suspected_shedding", operator: "eq", value: true }],
  },
  {
    id: "shift_work",
    kind: "conditional",
    prompt: "Do you do shift work or highly irregular working hours?",
    answerType: "boolean",
    showWhen: [{ fact: "suspected_shedding", operator: "eq", value: true }],
  },
  {
    id: "high_stress_load",
    kind: "conditional",
    prompt: "Would you describe your current stress load as consistently high?",
    answerType: "boolean",
    showWhen: [{ fact: "suspected_shedding", operator: "eq", value: true }],
  },
  {
    id: "overtraining",
    kind: "conditional",
    prompt: "Do you train at a very high intensity with limited recovery?",
    answerType: "boolean",
    showWhen: [{ fact: "suspected_shedding", operator: "eq", value: true }],
  },

  {
    id: "tight_hairstyles_or_extensions",
    kind: "conditional",
    prompt: "Do you regularly wear tight hairstyles, braids, extensions, or wigs that place tension on the hairline?",
    answerType: "boolean",
    showWhen: [{ fact: "possible_breakage_pattern", operator: "eq", value: true }],
  },
  {
    id: "frequent_helmet_or_headgear",
    kind: "conditional",
    prompt: "Do you frequently wear helmets, tight caps, or other headgear?",
    answerType: "boolean",
    showWhen: [{ fact: "possible_breakage_pattern", operator: "eq", value: true }],
  },
  {
    id: "contact_sports_or_headgear_sport",
    kind: "conditional",
    prompt: "Do you participate in contact sports or sports with tight or repetitive headgear?",
    answerType: "boolean",
    showWhen: [{ fact: "possible_breakage_pattern", operator: "eq", value: true }],
  },
  {
    id: "heat_or_chemical_styling",
    kind: "conditional",
    prompt: "Do you frequently use harsh heat styling, bleaching, relaxing, or strong cosmetic treatments?",
    answerType: "boolean",
    showWhen: [{ fact: "possible_breakage_pattern", operator: "eq", value: true }],
  },

  {
    id: "treatment_history",
    kind: "conditional",
    prompt: "Have you used any hair-loss treatments before?",
    answerType: "multi_select",
    options: [
      { value: "finasteride", label: "Finasteride" },
      { value: "dutasteride", label: "Dutasteride" },
      { value: "topical_minoxidil", label: "Topical minoxidil" },
      { value: "oral_minoxidil", label: "Oral minoxidil" },
      { value: "prp", label: "PRP" },
      { value: "other", label: "Other" },
      { value: "none", label: "None" },
    ],
    showWhen: [{ fact: "suspected_patterned_loss", operator: "eq", value: true }],
  },
];
